<a href="https://colab.research.google.com/github/sruthi-pa/first-git/blob/main/Day2p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("my name is {}".format("sruthi"))

my name is sruthi


In [ ]:
a="sruthi"

In [ ]:
a[:6]

'sruthi'

In [ ]:
#list

In [ ]:
[1,2,3,'m']

[1, 2, 3, 'm']

In [ ]:
a=['a',2,5]

In [ ]:
a

['a', 2, 5]

In [ ]:
a.append('d')

In [ ]:
a

['a', 2, 5, 'd']

In [ ]:
a[0]

'a'

In [ ]:
a[0:]

['a', 2, 5, 'd']

In [ ]:
a[2:3]

[5]

In [ ]:
a[1:3]

[2, 5]

In [ ]:
my_list=["a","b"]
my_list

['a', 'b']

In [ ]:
my_list.append('c')

In [ ]:
my_list

['a', 'b', 'c']

In [ ]:
my_list[0]="n"

In [ ]:
my_list

['n', 'b', 'c']

In [ ]:
nest=[1,2,[3,4]]

In [ ]:
nest

[1, 2, [3, 4]]

In [ ]:
nest[2:]

[[3, 4]]

In [ ]:
nest[2][1]

4

In [ ]:
nest[2][0]

3

In [ ]:
nest=[1,2,5,[3,4,["target","hello"]]]

In [ ]:
nest[3][2][1][1]

'e'

In [ ]:
#dictionary

In [ ]:
d={'key':"value","key2":123}

In [ ]:
d["key"]

'value'

In [ ]:
d["key2"]

123

In [ ]:
d={"k1":[1,2,3]}

In [ ]:
a=d["k1"][1]

In [ ]:
a

2

In [ ]:
d={"k1":{"k2":[1,2,3]}}

In [ ]:
d["k1"]["k2"][2]

3

In [ ]:
d["k1"]["k2"]

[1, 2, 3]

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
#tuple(immutable)

In [ ]:
(1,2,3)

(1, 2, 3)

In [ ]:
a=(1,5,6)

In [ ]:
a

(1, 5, 6)

In [ ]:
a[0]

1

In [ ]:
#set

In [ ]:
{1,2,3,}

{1, 2, 3}

In [ ]:
{1,2,2,3}

{1, 2, 3}

In [ ]:
s={1,2,3,4}

In [ ]:
s.add(6)

In [ ]:
s

{1, 2, 3, 4, 6}

In [ ]:
#comparison operators

In [ ]:
1>6

False

In [ ]:
6>1

True

In [ ]:
6==3

False

In [ ]:
6==6

True

In [ ]:
"a"=="e"

False

day=6-1-22 four

In [ ]:
l=[1,2,3,[7,'a']]
l[3][0]

7

In [ ]:
0==3

False

In [ ]:
'as'<'as'

False

In [ ]:
1<2 and 2>3

False

In [ ]:
True or False

True

In [ ]:
if 1<2:
  print("not equal")
else:
    print("equal")

not equal


In [ ]:
if True:
  x=2+2
  print(x)

4


In [ ]:
n=int(input("enter a number"))
a=int(input("enter second number"))
s=n+a
print(s)

enter a number2
enter second number3
5


In [ ]:
if 1==2:
  print("first")
elif(3==5):
  print("second")
elif(4==7):
  print("third")
else:
  print("last")      

last


In [ ]:
s=[1,2,356,78]
for m in s:
  print(m)

1
2
356
78


In [ ]:
for i in range(3):
  print("hello")

hello
hello
hello


In [ ]:
i=1
while(i<5):
  print("i is {}".format(i))
  i=i+1

i is 1
i is 2
i is 3
i is 4


In [ ]:
range(0,5)

range(0, 5)

In [ ]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [ ]:
a=[1,2,3,56]
out=[]
for i in a:
    out.append(i**2)
print(out)

[1, 4, 9, 3136]


In [ ]:
[i**2 for i in a]

[1, 4, 9, 3136]

In [ ]:
i=1
while(i<10):
  print("i is {}".format(i))
  i=i+1

i is 1
i is 2
i is 3
i is 4
i is 5
i is 6
i is 7
i is 8
i is 9


In [ ]:
def my(param1):
  print(param1)

In [ ]:
my("sruthi")

sruthi


In [ ]:
def my_name(name):
  print("my name is "+ name)


In [ ]:
my_name("habi")

my name is habi


In [ ]:
def square(num):
  return( num**2)

In [ ]:
a=square(2)
print(a)

4


In [ ]:
square(3)

9

In [ ]:
def times(var):
  return var*2

In [ ]:
s=[1,2,3,4]
list(map(times,s))

[2, 4, 6, 8]

In [ ]:
a=input("enter the name")
print("hello "+a)

enter the namesruthi
hello sruthi


In [ ]:
a=input("enter a number")
b=input("enter next number")
if(a>b):
  print("{} is greater".format(a))
else:
  print("{} is greater".format(b))  

enter a number3
enter next number6
6 is greater


In [ ]:
def new(n):
  return(n%2)
  

In [ ]:
new(6)

0

In [ ]:
def my_var(num):
   m=num/6;
   print(m)

In [ ]:
my_var(3)

0.5


In [ ]:
type(my_var(3))

0.5


NoneType

In [ ]:
type(0.3)

float

In [ ]:
u=lambda var:var**2      #to define function using lambda without using def

In [ ]:
u(2)

4

In [ ]:
seq=[1,2,3,6]

In [ ]:
list(map(lambda num:num**3,seq))

[1, 8, 27, 216]

In [ ]:
list(filter(lambda num:num%2==0,seq))

[2, 6]

In [ ]:
list(map(lambda num:num%2==0,seq))

[False, True, False, True]

In [ ]:
#methods

In [ ]:
s="hello my name is sruthi"

In [ ]:
s.upper()

'HELLO MY NAME IS SRUTHI'

In [ ]:
s.lower()

'hello my name is sruthi'

In [ ]:
s="HELLO"

In [ ]:
s.upper()

'HELLO'

In [ ]:
s.split()

['HELLO']

In [ ]:
s="my first job"

In [ ]:
s.split()

['my', 'first', 'job']

In [ ]:
tweet="go sports! #sports"
tweet.split('#')

['go sports! ', 'sports']

In [ ]:
tweet.split('#')[0]

'go sports! '

In [ ]:
tweet.split('#')[1]

'sports'

In [ ]:
new="sports whole, day"

In [ ]:
new.split(',')

['sports whole', ' day']

In [ ]:
d={'k1':1,'k2':2,}


In [ ]:
d['k1']

1

In [ ]:
d.keys()

dict_keys(['k1', 'k2'])

In [ ]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [ ]:
d.values()

dict_values([1, 2])

In [ ]:
lst=[1,2,3]
lst.pop()

3

In [ ]:
lst.append(6)

In [ ]:
lst

[1, 2, 6]

In [ ]:
first=lst.pop(2)

In [ ]:
first

6

In [ ]:
lst.append(5)

In [ ]:
lst

[1, 2, 5]

In [ ]:
x=[(2,3),(4,5),(6,7)]

In [ ]:
x[0]

(2, 3)

In [ ]:
x[0][0]

2

In [ ]:
x[0][1]

3

In [ ]:
for item in x:
  print(item)

(2, 3)
(4, 5)
(6, 7)


In [ ]:
for (a,b) in x:
  print(a)

2
4
6


In [ ]:
for (a,b) in x:
  print(b)

3
5
7


In [ ]:
#python data analysis library-numpy

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3]
a=np.array(my_list)    #to convert list to an array

In [ ]:
a

array([1, 2, 3])

In [ ]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,210,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,9)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [ ]:
np.eye(4)  #identitiy matrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,5)

array([[0.23051293, 0.69347968, 0.24756019, 0.6787392 , 0.5587634 ],
       [0.36193104, 0.23381039, 0.39067312, 0.42174042, 0.32312083],
       [0.53343901, 0.13251537, 0.12208468, 0.25083533, 0.8877585 ],
       [0.84856566, 0.58370608, 0.79958333, 0.27621503, 0.57401429],
       [0.05668617, 0.72835387, 0.82512161, 0.08575326, 0.57833216]])

In [ ]:
np.random.rand(5)

array([0.68250131, 0.94789279, 0.64318423, 0.96744559, 0.19281066])

In [ ]:
np.random.randn(2)#standard normal distribution

array([-0.04037079, -0.61237339])

In [ ]:
np.random.randint(1,100)   

34

In [ ]:
np.random.randint(1,100,10)

array([92, 67, 65,  6, 21, 80, 60, 60,  9, 21])

In [ ]:
arr=[1,2,3,5,6,7,8,9]

In [ ]:
arr=np.array(arr)

In [ ]:
arr.reshape(2,4)

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [ ]:
a=np.random.randint(0,50,10)

In [ ]:
a

array([29, 20, 12, 39, 30,  8,  6, 38, 14, 29])

In [ ]:
a.max()

39

In [ ]:
a.min()

6

In [ ]:
a.argmax()    #position of maximum

3

In [ ]:
a.argmin()     #position of minimum

6

In [ ]:
a.shape

(10,)

In [ ]:
a=[1,2,25,4]